name: Nightly Regression

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout target app
        uses: actions/checkout@v4
        with:
          repository: bernardooduarte/fullstack-e2e-playwright-example
          path: target-app

      - name: Start containers
        working-directory: target-app
        run: docker compose -f docker-compose.e2e.yml up -d --build

      - name: Wait backend
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3001; then exit 0; fi
            sleep 5
          done
          exit 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run tests
        working-directory: target-app/e2e
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright test

      - name: Stop containers
        if: always()
        working-directory: target-app
        run: docker compose -f docker-compose.e2e.yml down